force-app/main/default/objects/Carro__c/Carro__c.object-meta.xml
<CustomObject>
    <label>Carro</label>
    <nameField>
        <label>Carro Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Cal1__c.field-meta.xml
<CustomField>
    <fullName>Cal1__c</fullName>
    <label>Cal1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Cal2__c.field-meta.xml
<CustomField>
    <fullName>Cal2__c</fullName>
    <label>Cal2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Lead_Auxilar_CTRL.cls
public with sharing class Lead_Auxilar_CTRL {
	public Double intTotal{get; set;}
	public List<Lead> ListLead{get; set;}
	public Lead candidato{get; set;}
	public Carro__c carritos{get; set;}
	
	public Lead_Auxilar_CTRL(ApexPages.StandardController controller) {
		this.candidato= (Lead)controller.getRecord();
		intTotal= candidato.Cal1__c + candidato.Cal2__c;
		system.debug('~~~ Carrito: ' + carritos);
	}
}