force-app/main/default/objects/Lead/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Codigo Postal</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DailyLeadProcessorTest.cls
@isTest
private class DailyLeadProcessorTest {
    public static String cron = '0 0 0 8 6 ? 2033';
    static testMethod void testLeadProcessor() {
        List<Lead> lds = new List<Lead>();
        for(Integer i = 0; i < 200; i++) {
            Lead ld = new Lead(
            					Company = 'Cmp' + i,
			                    LastName = 'lst' + i,
            			        Status = 'Open',
            			        LeadSource = '',
			                    Codigo_Postal__c = 12345,
			                	Calle__c = 'Street');
            lds.add(ld);
        }
        insert lds;
        
        test.startTest();
        	String jbId = System.Schedule('testSchedule', cron, new DailyLeadProcessor());
        test.stopTest();
    }
}