force-app/main/default/objects/Lead/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Codigo Postal</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadProcessorTest.cls
@isTest
private class LeadProcessorTest {

    @testSetup 
    static void setup() {
        List<Lead> lds = new List<Lead>();
        for(Integer i = 0; i < 200; i++) {
            lds.add(
                new Lead(
                    Company = 'Cmp' + i,
                    LastName = 'lst' + i,
                    Status = 'Open',
                    LeadSource = 'Other',
                    Codigo_Postal__c = 12345,
                	Calle__c = 'Street')
            );
        }
        insert lds;
    }

    static testMethod void test() {        
        Test.startTest();
        LeadProcessor ldp = new LeadProcessor();
        Id batchId = Database.executeBatch(ldp);
        Test.stopTest();
    }
    
}